### ISSUE TITLE
Control of lambda0 and the corresponding support size?

### ISSUE THREAD

**Issue by vtshen** [hazimehh/L0Learn#22]
From the L0Learn.fit results, it looks like the lambda0 is computed based on the data, so we could not control the corresponding support size, even using the argument scaleDownFactor does not help. I was wondering if there is a way to control the support size, say, from 1 to 20, or this feature is a future update, or this issue is not a big concern?

Thanks

```
# code used as an example
data <- GenSynthetic(n=500,p=1000,k=50,seed=1)
X = data$X
y = data$y
fit1 <- L0Learn.fit(X, y, penalty="L0", algorithm="CD", nLambda=50, scaleDownFactor = 1-1e-16)
print(fit1)
```

**Comment by hazimehh** [comment]
Thanks for the suggestion!  The Lagrangian formulation of the L0 problem (which L0Learn solves) is not guaranteed to have a solution with a specific support size, e.g., there can be datasets for which no parameter lambda gives exactly 20 non-zeros (even if we're solving the problem to optimality).

If scaleDownFactor is not working, you can also try supplying your own grid of Lambdas. For your example this can be done along the lines of:

```R
userLambda[[1]] <- seq(from=0.026, to=0.008, length.out=100) # generate a sequence of 100 lambda values between 0.026 and 0.008
fit <- L0Learn.fit(X, y, penalty="L0", autoLambda=FALSE, lambdaGrid=userLambda)
print(fit)
```
This adds the support size 8 (which was previously missing) but does not produce every possible support size between 1 and 20. Experimenting more with the granularity of the lambda grid might improve this..

**Comment by vtshen** [comment]
Got it. Thanks for the help and the package.
