### ISSUE TITLE
L1L2 and L0L1L2

### ISSUE THREAD

**Issue by talegari** [hazimehh/L0Learn#35]
Hi,

Nice package! Thanks.

Are there plans to implement L1L2 (elastic net) and L0L1L2? (I do not know if latter makes sense).

**Comment by hazimehh** [comment]
Thanks! There are several fast packages for elastic net so we're not planning to add support. Regarding L0L1L2, tuning can become computationally prohibitive.. Generally, we recommend using the L0L2 estimator as it performs well across a wide range of real and synthetic datasets (see the experiments section in https://arxiv.org/abs/1803.01454 )
