### ISSUE TITLE
Allowing for positivity or box constraints on fitted coefficients?

### ISSUE THREAD

**Issue by tomwenseleers** [hazimehh/L0Learn#43]
Not sure if this would be possible at all - but do you think it might be possible to support positivity or box constraints on the fitted coefficients, similar to what is possible using the arguments lower.limits and upper.limits in glmnet?

**Comment by rahulmaz** [comment]
We have a branch of L0Learn that solves problems with non-negativity constraints: https://github.com/hazimehh/L0Learn/tree/nng

To install, you’ll need to run the following in R:
library(devtools) 
install_github("hazimehh/L0Learn", ref="nng")

Thanks for bringing this up. Some others have also requested for this feature --- we plan to add this into the main package in the future.

**Comment by hazimehh** [comment]
In the nng branch, the nng constraints are added by default (they cannot be turned off). If you're planning to use both versions of L0Learn (with and without nng),  it might be a good idea to install the nng version in a separate location.
